// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-cwMAZ0JB-aTBw1CIU7LL9tqAm1DYnA',
    appId: '1:585585062118:android:c0fe1cd4ffa43311dccb27',
    messagingSenderId: '585585062118',
    projectId: 'dompetkampusglobal',
    storageBucket: 'dompetkampusglobal.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-RZxRAnXp5H3dYGds2rRCJJZdFNXF9U',
    appId: '1:585585062118:ios:343652eb4ae0705fdccb27',
    messagingSenderId: '585585062118',
    projectId: 'dompetkampusglobal',
    storageBucket: 'dompetkampusglobal.firebasestorage.app',
    androidClientId: '585585062118-5taabevc3r2celdl52ncqtsahg2no148.apps.googleusercontent.com',
    iosClientId: '585585062118-3un4fuj4glcrojsvo2nfrsp2st8up2b4.apps.googleusercontent.com',
    iosBundleId: 'com.abdillahfajar.dompetkampusglobal',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKb2tAVz7Hdaur_ro3ImcoYWNrzjolJg',
    appId: '1:585585062118:web:46b4c745a939036edccb27',
    messagingSenderId: '585585062118',
    projectId: 'dompetkampusglobal',
    authDomain: 'dompetkampusglobal.firebaseapp.com',
    storageBucket: 'dompetkampusglobal.firebasestorage.app',
    measurementId: 'G-EM8184H60G',
  );
}
